### ISSUE TITLE
Unable to import

### ISSUE THREAD

**Issue by silvercondor** [bandprotocol/bandchain.js#20]
Stupid question but I'm trying to use this library in my react project but I'm unable to import it due to the library ending with .js

Any idea how do i resolve?

```
import React, { useEffect, useState } from 'react';
import { Client } from '@bandprotocol/bandchain.js';

export default App = () =>{
    return(
    <div></div>
    );
}

```

```
Failed to compile.

./src/components/app.js
Module not found: Can't resolve '@bandprotocol/bandchain.js' in '/mnt/g/Projects/test-app/src/components'
```

**Comment by evilpeach** [comment]
@silvercondor What version do you use? Currently, we've updated to 2.0.1 (Laozi version). Let's try this one.

**Comment by silvercondor** [comment]
i managed to get it working by using node v16. 

not too sure but would highly encourage not naming the library .js as it kinda conflicts with imports
