### ISSUE TITLE
example file outdated

### ISSUE THREAD

**Issue by GenericCreations** [bandprotocol/bandchain.js#8]
I was having an issue with a bad request code 400 after following the documentation page example usage ...

in the documentation it is instructed to use:
      const endpoint = 'http://poa-api.bandchain.org'

however diving into some recent changes made i found the modification to the endpoint:
       const endpoint = 'https://api-gm-lb.bandchain.org'

once i changed it cleared up the err 400 problem

hope this helps someone !

**Comment by evilpeach** [comment]
We've updated to the Laozi-supported version now.
